#!/bin/bash

rm -f output/graph*.png

for name in $(ls output/graph*.dot); do
	output=$(echo $name | sed -re s/\\.dot\$/.png/)
	
	echo "$name -> $output"
	
	rm -f $output
	dot $name -Tpng > $output
done

